# Generated by Django 5.0.3 on 2024-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoteapp", "0002_alter_author_born_date_alter_author_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
