# Generated by Django 5.0.3 on 2024-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoteapp", "0003_alter_author_fullname_alter_tag_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.DateField(null=True),
        ),
    ]
